name: helloworldmj
version: '1.0'
summary: OfflineIMAP
description: |
  OfflineIMAP is software that downloads your email mailbox(es) as local
  Maildirs. OfflineIMAP will synchronize both sides via IMAP.
confinement: devmode
base: core18

parts:
  helloworldmj:
    plugin: python
    python-version: python2
    source: https://github.com/snapcraft-docs/helloworldmj.git
    stage-packages:
      - python-six

apps:
  helloworldmj:
    command: bin/helloworldmj
